/**
 * The Syllable Trainer's words: two hundred common English words, each with the
 * syllables it is typed in.
 *
 * ## What is in it
 *
 * Words that turn up all the time in ordinary prose and are long enough to be
 * worth chunking: two syllables up to five, most of them two or three, because
 * that is what prose is made of, with enough long ones — information,
 * opportunity, international — that the rhythm is trained where it pays most.
 * Chosen for use, not to reach a number: nothing obscure, nothing a typist
 * would only meet in a dictionary.
 *
 * ## How the syllables are split
 *
 * Where a dictionary breaks the word — moun·tain, dif·fer·ent, in·for·ma·tion —
 * never at an arbitrary character. Those breaks follow how the word is said and
 * the parts it is built from, which is what makes a chunk something a typist
 * can hold in mind as one unit: "tion" is a thing the fingers learn once and
 * then meet everywhere. A single-letter syllable is kept where the word really
 * has one (a·bout, u·su·al·ly), because splitting it anywhere else would teach
 * the wrong chunk.
 *
 * ## Static
 *
 * The same words in the same order on every load, frozen, so a test built from
 * them depends only on how they were drawn, never on this data changing
 * underneath it. The count is stated on every entry as well as implied by the
 * syllables, so a mistyped entry is caught by the corpus tests rather than
 * shown to someone learning from it.
 *
 * No DOM, no React: data, checked under the engine's purity build.
 */

export interface SyllableWord {
  /** The whole word, lowercase. */
  readonly word: string
  /** Its syllables in order. Joined, they are the word. */
  readonly syllables: readonly string[]
  /** How many syllables it has: the length of `syllables`, stated so it can be checked. */
  readonly count: number
}

const ENTRIES: readonly SyllableWord[] = [
  { word: 'about', syllables: ['a', 'bout'], count: 2 },
  { word: 'after', syllables: ['af', 'ter'], count: 2 },
  { word: 'again', syllables: ['a', 'gain'], count: 2 },
  { word: 'also', syllables: ['al', 'so'], count: 2 },
  { word: 'always', syllables: ['al', 'ways'], count: 2 },
  { word: 'almost', syllables: ['al', 'most'], count: 2 },
  { word: 'answer', syllables: ['an', 'swer'], count: 2 },
  { word: 'around', syllables: ['a', 'round'], count: 2 },
  { word: 'away', syllables: ['a', 'way'], count: 2 },
  { word: 'because', syllables: ['be', 'cause'], count: 2 },
  { word: 'become', syllables: ['be', 'come'], count: 2 },
  { word: 'before', syllables: ['be', 'fore'], count: 2 },
  { word: 'begin', syllables: ['be', 'gin'], count: 2 },
  { word: 'behind', syllables: ['be', 'hind'], count: 2 },
  { word: 'better', syllables: ['bet', 'ter'], count: 2 },
  { word: 'between', syllables: ['be', 'tween'], count: 2 },
  { word: 'business', syllables: ['busi', 'ness'], count: 2 },
  { word: 'city', syllables: ['cit', 'y'], count: 2 },
  { word: 'common', syllables: ['com', 'mon'], count: 2 },
  { word: 'country', syllables: ['coun', 'try'], count: 2 },
  { word: 'during', syllables: ['dur', 'ing'], count: 2 },
  { word: 'early', syllables: ['ear', 'ly'], count: 2 },
  { word: 'enough', syllables: ['e', 'nough'], count: 2 },
  { word: 'even', syllables: ['e', 'ven'], count: 2 },
  { word: 'ever', syllables: ['ev', 'er'], count: 2 },
  { word: 'father', syllables: ['fa', 'ther'], count: 2 },
  { word: 'follow', syllables: ['fol', 'low'], count: 2 },
  { word: 'forward', syllables: ['for', 'ward'], count: 2 },
  { word: 'future', syllables: ['fu', 'ture'], count: 2 },
  { word: 'happen', syllables: ['hap', 'pen'], count: 2 },
  { word: 'letter', syllables: ['let', 'ter'], count: 2 },
  { word: 'little', syllables: ['lit', 'tle'], count: 2 },
  { word: 'market', syllables: ['mar', 'ket'], count: 2 },
  { word: 'matter', syllables: ['mat', 'ter'], count: 2 },
  { word: 'maybe', syllables: ['may', 'be'], count: 2 },
  { word: 'member', syllables: ['mem', 'ber'], count: 2 },
  { word: 'moment', syllables: ['mo', 'ment'], count: 2 },
  { word: 'money', syllables: ['mon', 'ey'], count: 2 },
  { word: 'morning', syllables: ['morn', 'ing'], count: 2 },
  { word: 'mother', syllables: ['moth', 'er'], count: 2 },
  { word: 'mountain', syllables: ['moun', 'tain'], count: 2 },
  { word: 'never', syllables: ['nev', 'er'], count: 2 },
  { word: 'number', syllables: ['num', 'ber'], count: 2 },
  { word: 'often', syllables: ['of', 'ten'], count: 2 },
  { word: 'only', syllables: ['on', 'ly'], count: 2 },
  { word: 'open', syllables: ['o', 'pen'], count: 2 },
  { word: 'order', syllables: ['or', 'der'], count: 2 },
  { word: 'other', syllables: ['oth', 'er'], count: 2 },
  { word: 'over', syllables: ['o', 'ver'], count: 2 },
  { word: 'paper', syllables: ['pa', 'per'], count: 2 },
  { word: 'people', syllables: ['peo', 'ple'], count: 2 },
  { word: 'person', syllables: ['per', 'son'], count: 2 },
  { word: 'picture', syllables: ['pic', 'ture'], count: 2 },
  { word: 'problem', syllables: ['prob', 'lem'], count: 2 },
  { word: 'question', syllables: ['ques', 'tion'], count: 2 },
  { word: 'rather', syllables: ['rath', 'er'], count: 2 },
  { word: 'reason', syllables: ['rea', 'son'], count: 2 },
  { word: 'second', syllables: ['sec', 'ond'], count: 2 },
  { word: 'simple', syllables: ['sim', 'ple'], count: 2 },
  { word: 'something', syllables: ['some', 'thing'], count: 2 },
  { word: 'student', syllables: ['stu', 'dent'], count: 2 },
  { word: 'system', syllables: ['sys', 'tem'], count: 2 },
  { word: 'table', syllables: ['ta', 'ble'], count: 2 },
  { word: 'teacher', syllables: ['teach', 'er'], count: 2 },
  { word: 'under', syllables: ['un', 'der'], count: 2 },
  { word: 'until', syllables: ['un', 'til'], count: 2 },
  { word: 'very', syllables: ['ver', 'y'], count: 2 },
  { word: 'water', syllables: ['wa', 'ter'], count: 2 },
  { word: 'window', syllables: ['win', 'dow'], count: 2 },
  { word: 'without', syllables: ['with', 'out'], count: 2 },
  { word: 'woman', syllables: ['wom', 'an'], count: 2 },
  { word: 'within', syllables: ['with', 'in'], count: 2 },
  { word: 'travel', syllables: ['trav', 'el'], count: 2 },
  { word: 'public', syllables: ['pub', 'lic'], count: 2 },
  { word: 'perhaps', syllables: ['per', 'haps'], count: 2 },
  { word: 'power', syllables: ['pow', 'er'], count: 2 },
  { word: 'result', syllables: ['re', 'sult'], count: 2 },
  { word: 'report', syllables: ['re', 'port'], count: 2 },
  { word: 'return', syllables: ['re', 'turn'], count: 2 },
  { word: 'service', syllables: ['ser', 'vice'], count: 2 },
  { word: 'special', syllables: ['spe', 'cial'], count: 2 },
  { word: 'subject', syllables: ['sub', 'ject'], count: 2 },
  { word: 'today', syllables: ['to', 'day'], count: 2 },
  { word: 'written', syllables: ['writ', 'ten'], count: 2 },
  { word: 'nothing', syllables: ['noth', 'ing'], count: 2 },
  { word: 'children', syllables: ['chil', 'dren'], count: 2 },
  { word: 'certain', syllables: ['cer', 'tain'], count: 2 },
  { word: 'center', syllables: ['cen', 'ter'], count: 2 },
  { word: 'doctor', syllables: ['doc', 'tor'], count: 2 },
  { word: 'office', syllables: ['of', 'fice'], count: 2 },
  { word: 'listen', syllables: ['lis', 'ten'], count: 2 },
  { word: 'modern', syllables: ['mod', 'ern'], count: 2 },
  { word: 'purpose', syllables: ['pur', 'pose'], count: 2 },
  { word: 'single', syllables: ['sin', 'gle'], count: 2 },
  { word: 'language', syllables: ['lan', 'guage'], count: 2 },
  { word: 'keyboard', syllables: ['key', 'board'], count: 2 },
  { word: 'practice', syllables: ['prac', 'tice'], count: 2 },
  { word: 'focus', syllables: ['fo', 'cus'], count: 2 },
  { word: 'motion', syllables: ['mo', 'tion'], count: 2 },
  { word: 'pattern', syllables: ['pat', 'tern'], count: 2 },
  { word: 'sometimes', syllables: ['some', 'times'], count: 2 },
  { word: 'someone', syllables: ['some', 'one'], count: 2 },
  { word: 'himself', syllables: ['him', 'self'], count: 2 },
  { word: 'myself', syllables: ['my', 'self'], count: 2 },
  { word: 'whether', syllables: ['wheth', 'er'], count: 2 },
  { word: 'social', syllables: ['so', 'cial'], count: 2 },
  { word: 'another', syllables: ['an', 'oth', 'er'], count: 3 },
  { word: 'already', syllables: ['al', 'read', 'y'], count: 3 },
  { word: 'anything', syllables: ['an', 'y', 'thing'], count: 3 },
  { word: 'anyone', syllables: ['an', 'y', 'one'], count: 3 },
  { word: 'beautiful', syllables: ['beau', 'ti', 'ful'], count: 3 },
  { word: 'character', syllables: ['char', 'ac', 'ter'], count: 3 },
  { word: 'company', syllables: ['com', 'pa', 'ny'], count: 3 },
  { word: 'computer', syllables: ['com', 'put', 'er'], count: 3 },
  { word: 'consider', syllables: ['con', 'sid', 'er'], count: 3 },
  { word: 'continue', syllables: ['con', 'tin', 'ue'], count: 3 },
  { word: 'develop', syllables: ['de', 'vel', 'op'], count: 3 },
  { word: 'different', syllables: ['dif', 'fer', 'ent'], count: 3 },
  { word: 'difficult', syllables: ['dif', 'fi', 'cult'], count: 3 },
  { word: 'everyone', syllables: ['ev', 'ery', 'one'], count: 3 },
  { word: 'everything', syllables: ['ev', 'ery', 'thing'], count: 3 },
  { word: 'example', syllables: ['ex', 'am', 'ple'], count: 3 },
  { word: 'family', syllables: ['fam', 'i', 'ly'], count: 3 },
  { word: 'government', syllables: ['gov', 'ern', 'ment'], count: 3 },
  { word: 'however', syllables: ['how', 'ev', 'er'], count: 3 },
  { word: 'important', syllables: ['im', 'por', 'tant'], count: 3 },
  { word: 'interest', syllables: ['in', 'ter', 'est'], count: 3 },
  { word: 'yesterday', syllables: ['yes', 'ter', 'day'], count: 3 },
  { word: 'together', syllables: ['to', 'geth', 'er'], count: 3 },
  { word: 'remember', syllables: ['re', 'mem', 'ber'], count: 3 },
  { word: 'several', syllables: ['sev', 'er', 'al'], count: 3 },
  { word: 'possible', syllables: ['pos', 'si', 'ble'], count: 3 },
  { word: 'probably', syllables: ['prob', 'a', 'bly'], count: 3 },
  { word: 'understand', syllables: ['un', 'der', 'stand'], count: 3 },
  { word: 'whatever', syllables: ['what', 'ev', 'er'], count: 3 },
  { word: 'tomorrow', syllables: ['to', 'mor', 'row'], count: 3 },
  { word: 'position', syllables: ['po', 'si', 'tion'], count: 3 },
  { word: 'decision', syllables: ['de', 'ci', 'sion'], count: 3 },
  { word: 'direction', syllables: ['di', 'rec', 'tion'], count: 3 },
  { word: 'suddenly', syllables: ['sud', 'den', 'ly'], count: 3 },
  { word: 'history', syllables: ['his', 'to', 'ry'], count: 3 },
  { word: 'natural', syllables: ['nat', 'u', 'ral'], count: 3 },
  { word: 'energy', syllables: ['en', 'er', 'gy'], count: 3 },
  { word: 'deliver', syllables: ['de', 'liv', 'er'], count: 3 },
  { word: 'discover', syllables: ['dis', 'cov', 'er'], count: 3 },
  { word: 'exercise', syllables: ['ex', 'er', 'cise'], count: 3 },
  { word: 'internet', syllables: ['in', 'ter', 'net'], count: 3 },
  { word: 'benefit', syllables: ['ben', 'e', 'fit'], count: 3 },
  { word: 'customer', syllables: ['cus', 'tom', 'er'], count: 3 },
  { word: 'recognize', syllables: ['rec', 'og', 'nize'], count: 3 },
  { word: 'carefully', syllables: ['care', 'ful', 'ly'], count: 3 },
  { word: 'beginning', syllables: ['be', 'gin', 'ning'], count: 3 },
  { word: 'following', syllables: ['fol', 'low', 'ing'], count: 3 },
  { word: 'condition', syllables: ['con', 'di', 'tion'], count: 3 },
  { word: 'property', syllables: ['prop', 'er', 'ty'], count: 3 },
  { word: 'potential', syllables: ['po', 'ten', 'tial'], count: 3 },
  { word: 'performance', syllables: ['per', 'for', 'mance'], count: 3 },
  { word: 'national', syllables: ['na', 'tion', 'al'], count: 3 },
  { word: 'industry', syllables: ['in', 'dus', 'try'], count: 3 },
  { word: 'production', syllables: ['pro', 'duc', 'tion'], count: 3 },
  { word: 'general', syllables: ['gen', 'er', 'al'], count: 3 },
  { word: 'various', syllables: ['var', 'i', 'ous'], count: 3 },
  { word: 'similar', syllables: ['sim', 'i', 'lar'], count: 3 },
  { word: 'completely', syllables: ['com', 'plete', 'ly'], count: 3 },
  { word: 'certainly', syllables: ['cer', 'tain', 'ly'], count: 3 },
  { word: 'finally', syllables: ['fi', 'nal', 'ly'], count: 3 },
  { word: 'recently', syllables: ['re', 'cent', 'ly'], count: 3 },
  { word: 'information', syllables: ['in', 'for', 'ma', 'tion'], count: 4 },
  { word: 'development', syllables: ['de', 'vel', 'op', 'ment'], count: 4 },
  { word: 'experience', syllables: ['ex', 'pe', 'ri', 'ence'], count: 4 },
  { word: 'education', syllables: ['ed', 'u', 'ca', 'tion'], count: 4 },
  { word: 'community', syllables: ['com', 'mu', 'ni', 'ty'], count: 4 },
  { word: 'particular', syllables: ['par', 'tic', 'u', 'lar'], count: 4 },
  { word: 'especially', syllables: ['es', 'pe', 'cial', 'ly'], count: 4 },
  { word: 'situation', syllables: ['sit', 'u', 'a', 'tion'], count: 4 },
  { word: 'environment', syllables: ['en', 'vi', 'ron', 'ment'], count: 4 },
  { word: 'technology', syllables: ['tech', 'nol', 'o', 'gy'], count: 4 },
  { word: 'individual', syllables: ['in', 'di', 'vid', 'u', 'al'], count: 5 },
  { word: 'opportunity', syllables: ['op', 'por', 'tu', 'ni', 'ty'], count: 5 },
  { word: 'organization', syllables: ['or', 'ga', 'ni', 'za', 'tion'], count: 5 },
  { word: 'relationship', syllables: ['re', 'la', 'tion', 'ship'], count: 4 },
  { word: 'conversation', syllables: ['con', 'ver', 'sa', 'tion'], count: 4 },
  { word: 'definitely', syllables: ['def', 'i', 'nite', 'ly'], count: 4 },
  { word: 'necessary', syllables: ['nec', 'es', 'sar', 'y'], count: 4 },
  { word: 'understanding', syllables: ['un', 'der', 'stand', 'ing'], count: 4 },
  { word: 'immediately', syllables: ['im', 'me', 'di', 'ate', 'ly'], count: 5 },
  { word: 'usually', syllables: ['u', 'su', 'al', 'ly'], count: 4 },
  { word: 'international', syllables: ['in', 'ter', 'na', 'tion', 'al'], count: 5 },
  { word: 'independent', syllables: ['in', 'de', 'pen', 'dent'], count: 4 },
  { word: 'significant', syllables: ['sig', 'nif', 'i', 'cant'], count: 4 },
  { word: 'interesting', syllables: ['in', 'ter', 'est', 'ing'], count: 4 },
  { word: 'actually', syllables: ['ac', 'tu', 'al', 'ly'], count: 4 },
  { word: 'quality', syllables: ['qual', 'i', 'ty'], count: 3 },
  { word: 'security', syllables: ['se', 'cu', 'ri', 'ty'], count: 4 },
  { word: 'university', syllables: ['u', 'ni', 'ver', 'si', 'ty'], count: 5 },
  { word: 'activity', syllables: ['ac', 'tiv', 'i', 'ty'], count: 4 },
  { word: 'reality', syllables: ['re', 'al', 'i', 'ty'], count: 4 },
  { word: 'material', syllables: ['ma', 'te', 'ri', 'al'], count: 4 },
  { word: 'political', syllables: ['po', 'lit', 'i', 'cal'], count: 4 },
  { word: 'economic', syllables: ['ec', 'o', 'nom', 'ic'], count: 4 },
]

export const SYLLABLE_CORPUS: readonly SyllableWord[] = Object.freeze(
  ENTRIES.map((entry) => Object.freeze({ ...entry, syllables: Object.freeze([...entry.syllables]) })),
)
